default_stages: [ "commit", "commit-msg", "push" ]

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        name: "End of file fixer"
    -   id: trailing-whitespace
        name: "Trailing whitespace fixer"
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: "Commit linter"
        stages: [commit-msg]
        additional_dependencies: [ '@commitlint/config-conventional' ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: "Linter"
        additional_dependencies:
          - pep8-naming
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: "Code formatter"
